Car.class: Car.java Vehicle.class Pickup.class GasPowered.class Brand.class
	javac Car.java

Vehicle.class: Vehicle.java
	javac Vehicle.java

Pickup.class: Pickup.java
	javac Pickup.java

GasPowered.class: GasPowered.java
	javac GasPowered.java

Brand.class: Brand.java
	javac Brand.java

run: Car.class
	java Car

clean:
	rm *.class

