LinkedList.class: LinkedList.java Node.class
	javac LinkedList.java

SimpleLinkedList.class: SimpleLinkedList.java Node.class
	javac SimpleLinkedList.java

Node.class: Node.java
	javac Node.java

run: LinkedList.class
	java LinkedList

runSimple: SimpleLinkedList.class
	java SimpleLinkedList

debug: LinkedList.class
	jdb LinkedList
